#lang racket

; 1.2 Procedures and the Processes They Generate
; What we have learned is analogous to that of someone who has learned the rules for how the pieces move in chess but knows...
; ..nothing of typical openings, tactics, or strategy.
; We must learn to visualize the processes generated by various types of procedures.


; 1.2.1 Linear Recursion and Iteration
; Factorial example: n! = n * (n - 1) for any positive integer n
; Linear recursive process grows linearly with n
(define (factorial n)
  (if (= n 1)
      1
      (* n (factorial (- n 1)))))
(factorial 9)